[meta]
title = "Bernhards's skillradar"
categories = [ "Tools", "Techniques", "Platforms", "Frameworks" ]
levels = [ "Novice", "Intermediate", "Advanced", "Veteran" ]

[[blips]]
category = 2
link = "https://k8s.io"
description = ""
title = "Kubernetes"
level = 3

  [[blips.changes]]
  date = "2019-08"
  newLevel = 3

[[blips]]
category = 2
link = "https://azure.com"
description = ""
title = "Azure"
level = 4

  [[blips.changes]]
  date = "2019-01"
  newLevel = 4

[[blips]]
category = 2
link = "https://aws.com"
description = ""
title = "AWS"
level = 0

  [[blips.changes]]
  date = "2019-08"
  newLevel = 0

[[blips]]
category = 2
link = "https://cloud.google.com"
description = ""
title = "Google Cloud"
level = 2

  [[blips.changes]]
  date = "2019-08"
  newLevel = 2

[[blips]]
category = 2
link = "https://firebase.com"
description = ""
title = "Firebase"
level = 3

  [[blips.changes]]
  date = "2019-08"
  newLevel = 3

[[blips]]
category = 3
link = "https://reactjs.org"
description = ""
title = "React"
level = 3

  [[blips.changes]]
  date = "2019-08"
  newLevel = 3

[[blips]]
category = 3
link = "https://vuejs.org"
description = ""
title = "Vue.js"
level = 2

  [[blips.changes]]
  date = "2019-08"
  newLevel = 2

[[blips]]
category = 3
link = "https://nodejs.org"
description = ""
title = "Node.js"
level = 4

  [[blips.changes]]
  date = "2019-08"
  newLevel = 4

[[blips]]
category = 3
link = "https://angular.io"
description = ""
title = "Angular"
level = 4

  [[blips.changes]]
  date = "2019-08"
  newLevel = 4  

[[blibs]]
category = 1
title = "Infrastructure as Code"
description = ""
level = 2

  [[blibs.changes]]
  date = "2019-08"
  newLevel = 2

[[blibs]]
category = 1
title = "CI/CD"
description = ""
level = 5

  [[blibs.changes]]
  date = "2019-08"
  newLevel = 5

[[blibs]]
category = 1
title = "Test Driven Development"
description = ""
level = 5

  [[blibs.changes]]
  date = "2019-08"
  newLevel = 5

[[blibs]]
category = 1
title = "Software Architecture"
description = ""
level = 3

  [[blibs.changes]]
  date = "2019-08"
  newLevel = 3

[[blibs]]
category = 1
title = "Deeplearning"
description = ""
level = 1

  [[blibs.changes]]
  date = "2019-08"
  newLevel = 1

[[blibs]]
category = 1
title = "Data Analytics"
description = ""
level = 2

  [[blibs.changes]]
  date = "2019-08"
  newLevel = 2

[[blibs]]
category = 1
title = "Design"
description = ""
level = 5

  [[blibs.changes]]
  date = "2019-08"
  newLevel = 5

[[blibs]]
category = 1
title = "Static Site Generators"
description = ""
level = 3

  [[blibs.changes]]
  date = "2019-08"
  newLevel = 3

[[blibs]]
category = 1
title = "Docs as Code"
description = ""
level = 2

  [[blibs.changes]]
  date = "2019-08"
  newLevel = 2

[[blibs]]
category = 1
title = "DevOps"
description = ""
level = 5

  [[blibs.changes]]
  date = "2019-08"
  newLevel = 5
